#!/bin/sh

PREREQ=""

prereqs() {
  echo "${PREREQ}"
}

case "${1}" in
  prereqs)
    prereqs
    exit 0
  ;;
esac

. /scripts/functions

. /etc/wireguard/initramfs

if [ -z "${PERSISTENT}" ]; then
  log_begin_msg 'Stopping wireguard boot network'
  ip link delete dev "${INTERFACE}"
  log_end_msg
fi
